#!/bin/bash

## Get home directory
user=$SUDO_USER
home=/home/$user/

## Downloads

# Intel-ucode	          Microcode update files for Intel CPUs
# xf86-input-libinput     Generic input driver for the X.Org server based on libinput
# networkmanager          Network connection manager and user applications
# network-manager-applet  Applet for managing network connections
# ttf-inconsolata         Monospace font for pretty code listings and for the terminal
# otf-font-awesome        Iconic font designed for Bootstrap
# demenu                  Fast and lightweight dynamic menu for X
# acpi                    Client for battery, power, and thermal readings
# tlp                     Linux Advanced Power Management
# ranger                  Simple, vim-like file manager
# gedit                   GNOME Text Editor
# compton                 X compositor that may fix tearing issues (Needed for transparency)
# feh                     Fast and light imlib2-based image viewer (Need for desktop background)
# lxappearance            Feature-rich GTK+ theme switcher of the LXDE Desktop
# pulseaudio              A featureful, general-purpose sound server
# pulseaudio-alsa         ALSA Configuration for PulseAudio
# alsa-utils              An alternative implementation of Linux sound support
# arc-gtk-theme           A flat theme with transparent elements for GTK 3, GTK 2 and Gnome-Shell
# maim                    Utility to take a screenshot using imlib2

pacman -Syu intel-ucode xf86-input-libinput networkmanager network-manager-applet ttf-inconsolata otf-font-awesome dmenu acpi tlp ranger gedit compton feh lxappearance pulseaudio pulseaudio-alsa alsa-utils arc-gtk-theme maim

## Distribute config files
mkdir -v -p $home/.config/i3
cp -v config_files/i3config $home.config/i3/config
cp -v config_files/i3blocks.conf $home.config/i3/i3blocks.conf
cp -v config_files/Xresources $home.Xresources
cp -v config_files/bashrc $home.bashrc
cp -v config_files/zshrc $home.zshrc
cp -v config_files/vimrc $home.vimrc
mkdir -v -p $home.scripts
cp -v -r scripts/* $home.scripts
chown -v -R $user $home.config/i3/config $home.Xresources $home.bashrc $home.scripts

## Enable wifi applet
systemctl enable NetworkManager.service
systemctl start NetworkManager.service
systemctl disable dhcpcd@eno1.service
systemctl disable netctl-auto@wlo1.service


## Setup touchpad

# Enables tap to click and natural scrolling
echo '
Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Option "NaturalScrolling" "true"
    Option "Tapping" "on"
    Driver "libinput"
EndSection' >> /usr/share/X11/xorg.conf.d/40-libinput.conf

