#!/bin/bash

## Get home directory
user=$(who | awk '{print $1}')
home=/home/$user/
## Downloads
pacman -Sy intel-ucode xf86-input-synaptics networkmanager network-manager-applet ttf-liberation ttf-font-awesome dmenu upower ranger gedit compton feh lxappearance rxvt-unicode urxvt-perls acpi vim pulseaudio pulseaudio-alsa arc-gtk-theme

## Distribute config files
cp config_files/i3config $home.config/i3/config
cp config_files/i3blocks.conf $home.config/i3/i3blocks.conf
cp config_files/Xresources $home.Xresources
cp config_files/bashrc $home.bashrc
chown $user $home.config/i3/config $home.Xresources $home.bashrc
mkdir $home.scripts
cp -r scripts/* $home.scripts

## Enable wifi applet
systemctl enable NetworkManager.service
systemctl disable dhcpcd@eno1.service
systemctl disable netctl-auto@wlo1.service
echo 'wifi enabled'

## Setup touchpad
echo '
Section "InputClass"
    Identifier "touchpad"
    Driver "synaptics"
    MatchIsTouchpad "on"
        Option "TapButton1" "1"
        Option "TapButton2" "3"
EndSection' >> /usr/share/X11/xorg.conf.d/70-synaptics.conf
echo 'tap to click enabled'
