#!/bin/bash

i3=~/myi3/config_files/
echo "Enter commit message: "
read message
echo "What would you like to add?"
read add
cp ~/.Xresources $i3/Xresources
cp ~/.config/i3/config $i3/i3config
cp ~/.bashrc $i3/bashrc
cp ~/.config/i3/i3blocks.conf $i3/i3blocks.conf
cp ~/.vimrc $i3/vimrc
cp -r ~/.scripts/* ~/myi3/scripts


git add $add
git commit -m "$message"
git push origin master
