#!/bin/bash

mgit=~/mygit/config_files/

cp ~/.Xresources $mgit/Xresources
cp ~/.config/i3/config $mgit/i3config
cp ~/.bashrc $mgit/bashrc

git add ~/mygit
git commit -m "i3 config"
git push origin master

