#!/bin/bash

i3=~/myi3/config_files/
echo "Enter commit message: "
read message
cp ~/.Xresources $i3/Xresources
cp ~/.config/i3/config $i3/i3config
cp ~/.bashrc $i3/bashrc
cp ~/.config/i3/i3blocks.conf $i3/i3blocks.conf
cp -r ~/.scripts/i3blocks/* ~/myi3/scripts/i3blocks
cp -r ~/.scripts/i3config/* ~/myi3/scripts/i3config


git add ~/myi3
git commit -m "$message"
git push origin master
