" Enable syntax
syntax on

" Display line numbers
set number

" Show partial commands
set showcmd

" turn hybrid line numbers on
:set number relativenumber
:set nu rnu

" Run xrdb when editing Xresources
	autocmd BufWritePost ~/.Xresources !xrdb %
